### ISSUE TITLE
Design Layout

### ISSUE THREAD

**Issue by tevissaur** [AlexanderLeino/Netflix-and-Grill#3]
* [x] Create wireframe
* [x] Choose CSS framework
* [x] Create layout on index.html
* [x] Create landing page

**Comment by tevissaur** [comment]
- ### [Link to Wireframe.cc](https://wireframe.cc/CWFgAL)
- ![netflix-and-grill](https://user-images.githubusercontent.com/65460369/131507031-e2d93f6f-0153-4bf9-8587-f74010a9cc6f.png)

**Comment by Linhbui88** [comment]
![NetflicandGrill-wireframe1](https://user-images.githubusercontent.com/87442413/131606024-0f3ee060-061b-46b0-832f-b37bcef49578.png)
![NetflicandGrill-wireframe2](https://user-images.githubusercontent.com/87442413/131606039-9347b7f2-eb68-4f68-9845-cc73d7b774de.png)
-Tailwind CSS and Animate CSS
-layout of frontpage and question form
