### ISSUE TITLE
Build API calls and connect to form

### ISSUE THREAD

**Issue by tevissaur** [AlexanderLeino/Netflix-and-Grill#4]
- [x] Create Form
- [x] Create Functions to handle form inputs

**Comment by Linhbui88** [comment]
[FORM]
1.  Is it going to be a kids-friendly movie night ?  YES / NO

2. How many people is going to join?
0-2
2-4
4-6
Over 6

3. What genres of movies do you like?
(dropdown menu listed all genres)

4.What tastes are you in the mood for?
(dropdown menu listed all tastes: sweet,/sour/ salty/ bitter,/and umami)
